import 'package:fake_cloud_firestore/fake_cloud_firestore.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:my_career_app/features/timeline/data/firestore_dependency_repository.dart';
import 'package:my_career_app/features/timeline/domain/event_dependency.dart';

void main() {
  late FakeFirebaseFirestore fakeFirestore;
  late FirestoreDependencyRepository repo;

  const testUserId = 'test-user-id';

  setUp(() {
    fakeFirestore = FakeFirebaseFirestore();
    repo = FirestoreDependencyRepository(testUserId, db: fakeFirestore);
  });

  EventDependency _makeDep({
    String id = 'dep-1',
    String sourceEventId = 'event-A',
    String targetEventId = 'event-B',
    int offsetMonths = 3,
    bool isAutoGenerated = false,
  }) {
    return EventDependency(
      id: id,
      sourceEventId: sourceEventId,
      targetEventId: targetEventId,
      offsetMonths: offsetMonths,
      isAutoGenerated: isAutoGenerated,
    );
  }

  group('FirestoreDependencyRepository', () {
    group('saveDependency() + fetchDependencies()', () {
      test('保存した依存関係を取得できること', () async {
        final dep = _makeDep();

        await repo.saveDependency(dep);
        final deps = await repo.fetchDependencies();

        expect(deps.length, equals(1));
      });

      test('取得した依存関係の id が一致すること', () async {
        final dep = _makeDep(id: 'dep-xyz');

        await repo.saveDependency(dep);
        final deps = await repo.fetchDependencies();

        expect(deps.first.id, equals('dep-xyz'));
      });

      test('取得した依存関係の offsetMonths が一致すること', () async {
        final dep = _makeDep(offsetMonths: 6);

        await repo.saveDependency(dep);
        final deps = await repo.fetchDependencies();

        expect(deps.first.offsetMonths, equals(6));
      });

      test('isAutoGenerated が正しく保存・取得されること', () async {
        final dep = _makeDep(isAutoGenerated: true);

        await repo.saveDependency(dep);
        final deps = await repo.fetchDependencies();

        expect(deps.first.isAutoGenerated, isTrue);
      });
    });

    group('deleteDependency()', () {
      test('削除後は依存関係が取得されないこと', () async {
        final dep = _makeDep();
        await repo.saveDependency(dep);

        await repo.deleteDependency(dep.id);
        final deps = await repo.fetchDependencies();

        expect(deps, isEmpty);
      });

      test('指定IDの依存関係のみが削除されること', () async {
        final d1 = _makeDep(id: 'd1');
        final d2 = _makeDep(id: 'd2', sourceEventId: 'event-C');
        await repo.saveDependency(d1);
        await repo.saveDependency(d2);

        await repo.deleteDependency('d1');
        final deps = await repo.fetchDependencies();

        expect(deps.length, equals(1));
        expect(deps.first.id, equals('d2'));
      });
    });

    group('updateDependency()', () {
      test('更新後の offsetMonths が取得されること', () async {
        final dep = _makeDep(offsetMonths: 2);
        await repo.saveDependency(dep);

        final updated = dep.copyWith(offsetMonths: 8);
        await repo.updateDependency(updated);
        final deps = await repo.fetchDependencies();

        expect(deps.first.offsetMonths, equals(8));
      });
    });

    group('fetchDependenciesForEvent()', () {
      test('sourceEventId が一致する依存関係を取得できること', () async {
        final dep = _makeDep(sourceEventId: 'event-X', targetEventId: 'event-Y');
        await repo.saveDependency(dep);

        final result = await repo.fetchDependenciesForEvent('event-X');

        expect(result.length, equals(1));
        expect(result.first.id, equals(dep.id));
      });

      test('targetEventId が一致する依存関係を取得できること', () async {
        final dep = _makeDep(sourceEventId: 'event-A', targetEventId: 'event-Z');
        await repo.saveDependency(dep);

        final result = await repo.fetchDependenciesForEvent('event-Z');

        expect(result.length, equals(1));
        expect(result.first.id, equals(dep.id));
      });

      test('関係のないイベントIDで検索すると空リストが返ること', () async {
        await repo.saveDependency(_makeDep());

        final result = await repo.fetchDependenciesForEvent('event-unknown');

        expect(result, isEmpty);
      });
    });

    group('deleteDependenciesForEvent()', () {
      test('指定イベントに関連する依存関係がすべて削除されること', () async {
        final d1 = _makeDep(id: 'd1', sourceEventId: 'target-event');
        final d2 = _makeDep(
            id: 'd2', sourceEventId: 'other', targetEventId: 'target-event');
        final d3 = _makeDep(id: 'd3', sourceEventId: 'unrelated', targetEventId: 'unrelated2');
        await repo.saveDependency(d1);
        await repo.saveDependency(d2);
        await repo.saveDependency(d3);

        await repo.deleteDependenciesForEvent('target-event');
        final remaining = await repo.fetchDependencies();

        expect(remaining.length, equals(1));
        expect(remaining.first.id, equals('d3'));
      });
    });
  });
}
