import 'package:flutter/foundation.dart';

/// イベント依存関係の種類
enum DependencyType {
  /// AがBの前提条件
  prerequisite('前提'),

  /// AによりBが発生
  consequence('結果'),

  /// AはBのN月前が期限
  deadline('期限'),

  /// AとBは常に一定間隔
  companion('連動');

  const DependencyType(this.label);

  /// 日本語ラベル
  final String label;
}

/// イベント間の依存関係を表すイミュータブルなモデル
@immutable
class EventDependency {
  /// 依存関係の一意識別子
  final String id;

  /// 依存元イベントID
  final String sourceEventId;

  /// 依存先イベントID
  final String targetEventId;

  /// 依存関係の種類
  final DependencyType type;

  /// ソースからターゲットへの月数オフセット
  final int offsetMonths;

  /// テンプレートから自動生成されたか
  final bool isAutoGenerated;

  const EventDependency({
    required this.id,
    required this.sourceEventId,
    required this.targetEventId,
    required this.type,
    required this.offsetMonths,
    this.isAutoGenerated = false,
  });

  /// 一部のプロパティを変更した新しい [EventDependency] インスタンスを生成する
  EventDependency copyWith({
    String? id,
    String? sourceEventId,
    String? targetEventId,
    DependencyType? type,
    int? offsetMonths,
    bool? isAutoGenerated,
  }) {
    return EventDependency(
      id: id ?? this.id,
      sourceEventId: sourceEventId ?? this.sourceEventId,
      targetEventId: targetEventId ?? this.targetEventId,
      type: type ?? this.type,
      offsetMonths: offsetMonths ?? this.offsetMonths,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is EventDependency &&
        other.id == id &&
        other.sourceEventId == sourceEventId &&
        other.targetEventId == targetEventId &&
        other.type == type &&
        other.offsetMonths == offsetMonths &&
        other.isAutoGenerated == isAutoGenerated;
  }

  @override
  int get hashCode {
    return id.hashCode ^
        sourceEventId.hashCode ^
        targetEventId.hashCode ^
        type.hashCode ^
        offsetMonths.hashCode ^
        isAutoGenerated.hashCode;
  }
}
