import 'package:flutter/foundation.dart';

/// イベント間の依存関係を表すイミュータブルなモデル
@immutable
class EventDependency {
  /// 依存関係の一意識別子
  final String id;

  /// 依存元イベントID
  final String sourceEventId;

  /// 依存先イベントID
  final String targetEventId;

  /// ソースからターゲットへの月数オフセット
  final int offsetMonths;

  /// テンプレートから自動生成されたか
  final bool isAutoGenerated;

  const EventDependency({
    required this.id,
    required this.sourceEventId,
    required this.targetEventId,
    required this.offsetMonths,
    this.isAutoGenerated = false,
  });

  /// 一部のプロパティを変更した新しい [EventDependency] インスタンスを生成する
  EventDependency copyWith({
    String? id,
    String? sourceEventId,
    String? targetEventId,
    int? offsetMonths,
    bool? isAutoGenerated,
  }) {
    return EventDependency(
      id: id ?? this.id,
      sourceEventId: sourceEventId ?? this.sourceEventId,
      targetEventId: targetEventId ?? this.targetEventId,
      offsetMonths: offsetMonths ?? this.offsetMonths,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is EventDependency &&
        other.id == id &&
        other.sourceEventId == sourceEventId &&
        other.targetEventId == targetEventId &&
        other.offsetMonths == offsetMonths &&
        other.isAutoGenerated == isAutoGenerated;
  }

  @override
  int get hashCode {
    return id.hashCode ^
        sourceEventId.hashCode ^
        targetEventId.hashCode ^
        offsetMonths.hashCode ^
        isAutoGenerated.hashCode;
  }
}
