import 'package:my_career_app/features/timeline/domain/event_dependency.dart';
import 'package:my_career_app/features/timeline/domain/life_event.dart';

/// テスト用の [LifeEvent] を生成する。
///
/// テストが関心を持つフィールドだけを指定し、残りは既定値に任せる。
/// これにより「そのテストが何を見ているか」がシグネチャから読み取れる。
///
/// なお、ドメインモデル自身の仕様（コンストラクタ・JSON 変換・`copyWith`）を
/// 検証するテストでは、検証対象を隠さないためにこのビルダーを使わず
/// `LifeEvent(...)` を直接組み立てること。
LifeEvent buildLifeEvent({
  String id = 'event-1',
  String catalogId = 'joining-company',
  String date = '2024-01',
  String? endDate,
  String title = 'テストイベント',
  String description = '',
  EventStatus status = EventStatus.recorded,
  String? goalId,
  bool isGoal = false,
  int? budgetYen,
}) {
  return LifeEvent(
    id: id,
    catalogId: catalogId,
    date: date,
    endDate: endDate,
    title: title,
    description: description,
    status: status,
    goalId: goalId,
    isGoal: isGoal,
    budgetYen: budgetYen,
  );
}

/// テスト用の [EventDependency] を生成する。
EventDependency buildDependency({
  String id = 'dep-1',
  String sourceEventId = 'event-1',
  String targetEventId = 'event-2',
  int offsetMonths = 0,
  bool isAutoGenerated = false,
  DependencyStrength strength = DependencyStrength.soft,
}) {
  return EventDependency(
    id: id,
    sourceEventId: sourceEventId,
    targetEventId: targetEventId,
    offsetMonths: offsetMonths,
    isAutoGenerated: isAutoGenerated,
    strength: strength,
  );
}
