import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:uuid/uuid.dart';
import '../data/goal_template_data.dart';
import '../domain/event_dependency.dart';
import '../domain/goal_template.dart';
import '../domain/life_event.dart';
import 'dependency_provider.dart';
import 'timeline_events_provider.dart';

/// ゴールテンプレート適用の結果
class GoalExpansionResult {
  /// 生成されたイベント一覧（ゴールイベント含む）
  final List<LifeEvent> generatedEvents;

  /// 生成された依存関係一覧
  final List<EventDependency> generatedDependencies;

  const GoalExpansionResult({
    required this.generatedEvents,
    required this.generatedDependencies,
  });
}

/// ゴール日付文字列に月数を加算した文字列を返す
///
/// 年境界を正しく処理する（例: 2028-01 - 2 = 2027-11）。
String addMonthsToDate(String dateStr, int months) {
  final parts = dateStr.split('-');
  int year = int.parse(parts[0]);
  int month = int.parse(parts[1]) + months;

  while (month > 12) {
    year++;
    month -= 12;
  }
  while (month < 1) {
    year--;
    month += 12;
  }

  return '$year-${month.toString().padLeft(2, '0')}';
}

/// ゴールテンプレート選択→イベント群一括生成を管理するNotifier
class GoalTemplateNotifier extends Notifier<List<GoalTemplate>> {
  @override
  List<GoalTemplate> build() {
    return GoalTemplateRegistry.templates;
  }

  /// テンプレートを適用し、イベント群と依存関係を一括生成する
  ///
  /// [templateId] 適用するテンプレートのID
  /// [goalDate] ゴール日（yyyy-MM 形式）
  /// [goalTitle] ゴールイベントのタイトル
  Future<GoalExpansionResult> applyTemplate({
    required String templateId,
    required String goalDate,
    required String goalTitle,
  }) async {
    const uuid = Uuid();

    final template = state.firstWhere(
      (t) => t.id == templateId,
      orElse: () => throw ArgumentError('Template not found: $templateId'),
    );

    // ゴールイベントを生成
    final goalEventId = uuid.v4();
    final goalEvent = LifeEvent(
      id: goalEventId,
      date: goalDate,
      title: goalTitle,
      description: '',
      category: template.goalCategory,
      status: EventStatus.planned,
      goalId: goalEventId,
      isGoal: true,
    );

    // 関連イベントを生成
    final relatedEvents = <LifeEvent>[];
    for (final templateEvent in template.relatedEvents) {
      final eventDate =
          addMonthsToDate(goalDate, templateEvent.offsetMonthsFromGoal);
      final endDate = templateEvent.durationMonths != null
          ? addMonthsToDate(eventDate, templateEvent.durationMonths!)
          : null;

      relatedEvents.add(LifeEvent(
        id: uuid.v4(),
        date: eventDate,
        endDate: endDate,
        title: templateEvent.titleTemplate,
        description: '',
        category: templateEvent.category,
        status: EventStatus.planned,
        goalId: goalEventId,
        isGoal: false,
      ));
    }

    final allEvents = [goalEvent, ...relatedEvents];

    // 依存関係を生成（各関連イベント → ゴールイベント）
    final dependencies = <EventDependency>[];
    for (int i = 0; i < template.relatedEvents.length; i++) {
      final templateEvent = template.relatedEvents[i];
      final relatedEvent = relatedEvents[i];

      dependencies.add(EventDependency(
        id: uuid.v4(),
        sourceEventId: relatedEvent.id,
        targetEventId: goalEventId,
        offsetMonths: templateEvent.offsetMonthsFromGoal.abs(),
        isAutoGenerated: true,
      ));
    }

    // イベントを追加
    for (final event in allEvents) {
      await ref.read(timelineEventsProvider.notifier).addEvent(event);
    }

    // 依存関係を追加
    for (final dep in dependencies) {
      await ref.read(dependencyProvider.notifier).addDependency(dep);
    }

    return GoalExpansionResult(
      generatedEvents: allEvents,
      generatedDependencies: dependencies,
    );
  }
}

/// ゴールテンプレートの状態と適用操作を提供するProvider
final goalTemplateProvider =
    NotifierProvider<GoalTemplateNotifier, List<GoalTemplate>>(() {
  return GoalTemplateNotifier();
});
