// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYbWJveb0Pw2pRID79CdmdXFmoDXwnQpQ',
    appId: '1:373539746519:web:103064813e46035a92f692',
    messagingSenderId: '373539746519',
    projectId: 'my-career-app-559fd',
    authDomain: 'my-career-app-559fd.firebaseapp.com',
    storageBucket: 'my-career-app-559fd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASVYuw3A65X6uiMcrjmIvOHBPk2ssPKok',
    appId: '1:373539746519:android:951e955e9c8648c792f692',
    messagingSenderId: '373539746519',
    projectId: 'my-career-app-559fd',
    storageBucket: 'my-career-app-559fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwVwRwVBh0OOa60LrNwpIfR1TJvOLFgS4',
    appId: '1:373539746519:ios:a4704757fcfbf74d92f692',
    messagingSenderId: '373539746519',
    projectId: 'my-career-app-559fd',
    storageBucket: 'my-career-app-559fd.firebasestorage.app',
    iosBundleId: 'com.example.myCareerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwVwRwVBh0OOa60LrNwpIfR1TJvOLFgS4',
    appId: '1:373539746519:ios:a4704757fcfbf74d92f692',
    messagingSenderId: '373539746519',
    projectId: 'my-career-app-559fd',
    storageBucket: 'my-career-app-559fd.firebasestorage.app',
    iosBundleId: 'com.example.myCareerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYbWJveb0Pw2pRID79CdmdXFmoDXwnQpQ',
    appId: '1:373539746519:web:a42261724a39993f92f692',
    messagingSenderId: '373539746519',
    projectId: 'my-career-app-559fd',
    authDomain: 'my-career-app-559fd.firebaseapp.com',
    storageBucket: 'my-career-app-559fd.firebasestorage.app',
  );
}
