import 'package:cloud_firestore/cloud_firestore.dart';

import '../domain/event_dependency.dart';
import 'dependency_repository.dart';

/// Firestore を使用した [DependencyRepository] の実装
///
/// コレクションパス: `users/{userId}/dependencies`
class FirestoreDependencyRepository implements DependencyRepository {
  final String userId;
  final FirebaseFirestore _db;

  FirestoreDependencyRepository(this.userId, {FirebaseFirestore? db})
      : _db = db ?? FirebaseFirestore.instance;

  CollectionReference<Map<String, dynamic>> get _col =>
      _db.collection('users').doc(userId).collection('dependencies');

  @override
  Future<List<EventDependency>> fetchDependencies() async {
    final snapshot = await _col.get();
    return snapshot.docs.map(_fromDoc).toList();
  }

  @override
  Future<void> saveDependency(EventDependency dependency) async {
    await _col.doc(dependency.id).set(_toMap(dependency));
  }

  @override
  Future<void> updateDependency(EventDependency dependency) async {
    await _col.doc(dependency.id).update(_toMap(dependency));
  }

  @override
  Future<void> deleteDependency(String dependencyId) async {
    await _col.doc(dependencyId).delete();
  }

  @override
  Future<void> deleteDependenciesForEvent(String eventId) async {
    final deps = await fetchDependenciesForEvent(eventId);
    final batch = _db.batch();
    for (final dep in deps) {
      batch.delete(_col.doc(dep.id));
    }
    await batch.commit();
  }

  @override
  Future<List<EventDependency>> fetchDependenciesForEvent(
      String eventId) async {
    final sourceSnap =
        await _col.where('sourceEventId', isEqualTo: eventId).get();
    final targetSnap =
        await _col.where('targetEventId', isEqualTo: eventId).get();
    // 重複を除いてマージ
    final seen = <String>{};
    final result = <EventDependency>[];
    for (final doc in [...sourceSnap.docs, ...targetSnap.docs]) {
      if (seen.add(doc.id)) {
        result.add(_fromDoc(doc));
      }
    }
    return result;
  }

  Map<String, dynamic> _toMap(EventDependency d) => {
        'id': d.id,
        'sourceEventId': d.sourceEventId,
        'targetEventId': d.targetEventId,
        'offsetMonths': d.offsetMonths,
        'isAutoGenerated': d.isAutoGenerated,
      };

  EventDependency _fromDoc(QueryDocumentSnapshot<Map<String, dynamic>> doc) {
    final data = doc.data();
    return EventDependency(
      id: data['id'] as String,
      sourceEventId: data['sourceEventId'] as String,
      targetEventId: data['targetEventId'] as String,
      offsetMonths: data['offsetMonths'] as int? ?? 0,
      isAutoGenerated: data['isAutoGenerated'] as bool? ?? false,
    );
  }
}
