import 'package:flutter_test/flutter_test.dart';
import 'package:my_career_app/features/timeline/domain/event_dependency.dart';

void main() {
  group('EventDependency の仕様', () {
    test('正しいパラメータで EventDependency が生成されること', () {
      const dep = EventDependency(
        id: 'dep-1',
        sourceEventId: 'event-a',
        targetEventId: 'event-b',
        offsetMonths: 3,
      );

      expect(dep.id, 'dep-1');
      expect(dep.sourceEventId, 'event-a');
      expect(dep.targetEventId, 'event-b');
      expect(dep.offsetMonths, 3);
    });

    test('デフォルトの isAutoGenerated は false であること', () {
      const dep = EventDependency(
        id: 'dep-1',
        sourceEventId: 'event-a',
        targetEventId: 'event-b',
        offsetMonths: 0,
      );

      expect(dep.isAutoGenerated, isFalse);
    });

    test('isAutoGenerated を true に設定できること', () {
      const dep = EventDependency(
        id: 'dep-1',
        sourceEventId: 'event-a',
        targetEventId: 'event-b',
        offsetMonths: 6,
        isAutoGenerated: true,
      );

      expect(dep.isAutoGenerated, isTrue);
    });

    test('負の offsetMonths を設定できること', () {
      const dep = EventDependency(
        id: 'dep-1',
        sourceEventId: 'event-a',
        targetEventId: 'event-b',
        offsetMonths: -12,
      );

      expect(dep.offsetMonths, -12);
    });

    test('copyWith で一部のプロパティを変更した新しいインスタンスを生成できること', () {
      const dep = EventDependency(
        id: 'dep-1',
        sourceEventId: 'event-a',
        targetEventId: 'event-b',
        offsetMonths: 3,
      );

      final updated = dep.copyWith(offsetMonths: 6);

      expect(updated.offsetMonths, 6);
      expect(updated.id, 'dep-1');
      expect(updated.sourceEventId, 'event-a');
      expect(updated.targetEventId, 'event-b');
    });

    test('同じパラメータの2つのインスタンスは等しいこと', () {
      const dep1 = EventDependency(
        id: 'dep-1',
        sourceEventId: 'event-a',
        targetEventId: 'event-b',
        offsetMonths: 0,
        isAutoGenerated: true,
      );
      const dep2 = EventDependency(
        id: 'dep-1',
        sourceEventId: 'event-a',
        targetEventId: 'event-b',
        offsetMonths: 0,
        isAutoGenerated: true,
      );

      expect(dep1, equals(dep2));
    });

    test('異なるパラメータの2つのインスタンスは等しくないこと', () {
      const dep1 = EventDependency(
        id: 'dep-1',
        sourceEventId: 'event-a',
        targetEventId: 'event-b',
        offsetMonths: 3,
      );
      const dep2 = EventDependency(
        id: 'dep-2',
        sourceEventId: 'event-a',
        targetEventId: 'event-b',
        offsetMonths: 3,
      );

      expect(dep1, isNot(equals(dep2)));
    });
  });
}
