import 'package:flutter_test/flutter_test.dart';
import 'package:my_career_app/features/timeline/domain/event_dependency.dart';

void main() {
  group('DependencyType の仕様', () {
    test('DependencyType は4つの値を持つこと', () {
      expect(DependencyType.values.length, 4);
    });

    test('DependencyType の値に prerequisite, consequence, deadline, companion が含まれること', () {
      expect(DependencyType.values, contains(DependencyType.prerequisite));
      expect(DependencyType.values, contains(DependencyType.consequence));
      expect(DependencyType.values, contains(DependencyType.deadline));
      expect(DependencyType.values, contains(DependencyType.companion));
    });

    test('prerequisite の label が 前提 であること', () {
      expect(DependencyType.prerequisite.label, '前提');
    });

    test('consequence の label が 結果 であること', () {
      expect(DependencyType.consequence.label, '結果');
    });

    test('deadline の label が 期限 であること', () {
      expect(DependencyType.deadline.label, '期限');
    });

    test('companion の label が 連動 であること', () {
      expect(DependencyType.companion.label, '連動');
    });
  });

  group('EventDependency の仕様', () {
    test('正しいパラメータで EventDependency が生成されること', () {
      const dep = EventDependency(
        id: 'dep-1',
        sourceEventId: 'event-a',
        targetEventId: 'event-b',
        type: DependencyType.prerequisite,
        offsetMonths: 3,
      );

      expect(dep.id, 'dep-1');
      expect(dep.sourceEventId, 'event-a');
      expect(dep.targetEventId, 'event-b');
      expect(dep.type, DependencyType.prerequisite);
      expect(dep.offsetMonths, 3);
    });

    test('デフォルトの isAutoGenerated は false であること', () {
      const dep = EventDependency(
        id: 'dep-1',
        sourceEventId: 'event-a',
        targetEventId: 'event-b',
        type: DependencyType.companion,
        offsetMonths: 0,
      );

      expect(dep.isAutoGenerated, isFalse);
    });

    test('isAutoGenerated を true に設定できること', () {
      const dep = EventDependency(
        id: 'dep-1',
        sourceEventId: 'event-a',
        targetEventId: 'event-b',
        type: DependencyType.consequence,
        offsetMonths: 6,
        isAutoGenerated: true,
      );

      expect(dep.isAutoGenerated, isTrue);
    });

    test('負の offsetMonths を設定できること', () {
      const dep = EventDependency(
        id: 'dep-1',
        sourceEventId: 'event-a',
        targetEventId: 'event-b',
        type: DependencyType.deadline,
        offsetMonths: -12,
      );

      expect(dep.offsetMonths, -12);
    });

    test('copyWith で一部のプロパティを変更した新しいインスタンスを生成できること', () {
      const dep = EventDependency(
        id: 'dep-1',
        sourceEventId: 'event-a',
        targetEventId: 'event-b',
        type: DependencyType.prerequisite,
        offsetMonths: 3,
      );

      final updated = dep.copyWith(offsetMonths: 6, type: DependencyType.deadline);

      expect(updated.offsetMonths, 6);
      expect(updated.type, DependencyType.deadline);
      expect(updated.id, 'dep-1');
      expect(updated.sourceEventId, 'event-a');
      expect(updated.targetEventId, 'event-b');
    });

    test('同じパラメータの2つのインスタンスは等しいこと', () {
      const dep1 = EventDependency(
        id: 'dep-1',
        sourceEventId: 'event-a',
        targetEventId: 'event-b',
        type: DependencyType.companion,
        offsetMonths: 0,
        isAutoGenerated: true,
      );
      const dep2 = EventDependency(
        id: 'dep-1',
        sourceEventId: 'event-a',
        targetEventId: 'event-b',
        type: DependencyType.companion,
        offsetMonths: 0,
        isAutoGenerated: true,
      );

      expect(dep1, equals(dep2));
    });

    test('異なるパラメータの2つのインスタンスは等しくないこと', () {
      const dep1 = EventDependency(
        id: 'dep-1',
        sourceEventId: 'event-a',
        targetEventId: 'event-b',
        type: DependencyType.prerequisite,
        offsetMonths: 3,
      );
      const dep2 = EventDependency(
        id: 'dep-2',
        sourceEventId: 'event-a',
        targetEventId: 'event-b',
        type: DependencyType.prerequisite,
        offsetMonths: 3,
      );

      expect(dep1, isNot(equals(dep2)));
    });
  });
}
