import 'package:flutter_test/flutter_test.dart';
import 'package:my_career_app/features/timeline/domain/event_dependency.dart';

void main() {
  group('EventDependency の仕様', () {
    test('正しいパラメータで EventDependency が生成されること', () {
      const dep = EventDependency(
        id: 'dep-1',
        sourceEventId: 'event-a',
        targetEventId: 'event-b',
        offsetMonths: 3,
      );

      expect(dep.id, 'dep-1');
      expect(dep.sourceEventId, 'event-a');
      expect(dep.targetEventId, 'event-b');
      expect(dep.offsetMonths, 3);
    });

    test('デフォルトの isAutoGenerated は false であること', () {
      const dep = EventDependency(
        id: 'dep-1',
        sourceEventId: 'event-a',
        targetEventId: 'event-b',
        offsetMonths: 0,
      );

      expect(dep.isAutoGenerated, isFalse);
    });

    test('isAutoGenerated を true に設定できること', () {
      const dep = EventDependency(
        id: 'dep-1',
        sourceEventId: 'event-a',
        targetEventId: 'event-b',
        offsetMonths: 6,
        isAutoGenerated: true,
      );

      expect(dep.isAutoGenerated, isTrue);
    });

    test('負の offsetMonths を設定できること', () {
      const dep = EventDependency(
        id: 'dep-1',
        sourceEventId: 'event-a',
        targetEventId: 'event-b',
        offsetMonths: -12,
      );

      expect(dep.offsetMonths, -12);
    });

    test('デフォルトの strength は DependencyStrength.soft であること', () {
      const dep = EventDependency(
        id: 'dep-1',
        sourceEventId: 'event-a',
        targetEventId: 'event-b',
        offsetMonths: 0,
      );

      expect(dep.strength, DependencyStrength.soft);
    });

    test('strength を hard に設定できること', () {
      const dep = EventDependency(
        id: 'dep-1',
        sourceEventId: 'event-a',
        targetEventId: 'event-b',
        offsetMonths: 0,
        strength: DependencyStrength.hard,
      );

      expect(dep.strength, DependencyStrength.hard);
    });

    test('strength が toJson/fromJson でラウンドトリップすること（hard）', () {
      const dep = EventDependency(
        id: 'dep-1',
        sourceEventId: 'event-a',
        targetEventId: 'event-b',
        offsetMonths: 0,
        strength: DependencyStrength.hard,
      );

      final json = dep.toJson();
      final restored = EventDependency.fromJson(json);

      expect(restored.strength, DependencyStrength.hard);
    });

    test('strength が toJson/fromJson でラウンドトリップすること（soft）', () {
      const dep = EventDependency(
        id: 'dep-1',
        sourceEventId: 'event-a',
        targetEventId: 'event-b',
        offsetMonths: 0,
        strength: DependencyStrength.soft,
      );

      final json = dep.toJson();
      final restored = EventDependency.fromJson(json);

      expect(restored.strength, DependencyStrength.soft);
    });

    test('copyWith で一部のプロパティを変更した新しいインスタンスを生成できること', () {
      const dep = EventDependency(
        id: 'dep-1',
        sourceEventId: 'event-a',
        targetEventId: 'event-b',
        offsetMonths: 3,
      );

      final updated = dep.copyWith(offsetMonths: 6);

      expect(updated.offsetMonths, 6);
      expect(updated.id, 'dep-1');
      expect(updated.sourceEventId, 'event-a');
      expect(updated.targetEventId, 'event-b');
    });

    test('copyWith で strength を変更できること', () {
      const dep = EventDependency(
        id: 'dep-1',
        sourceEventId: 'event-a',
        targetEventId: 'event-b',
        offsetMonths: 0,
      );

      final updated = dep.copyWith(strength: DependencyStrength.hard);

      expect(updated.strength, DependencyStrength.hard);
    });

    test('同じパラメータの2つのインスタンスは等しいこと', () {
      const dep1 = EventDependency(
        id: 'dep-1',
        sourceEventId: 'event-a',
        targetEventId: 'event-b',
        offsetMonths: 0,
        isAutoGenerated: true,
        strength: DependencyStrength.hard,
      );
      const dep2 = EventDependency(
        id: 'dep-1',
        sourceEventId: 'event-a',
        targetEventId: 'event-b',
        offsetMonths: 0,
        isAutoGenerated: true,
        strength: DependencyStrength.hard,
      );

      expect(dep1, equals(dep2));
    });

    test('異なるパラメータの2つのインスタンスは等しくないこと', () {
      const dep1 = EventDependency(
        id: 'dep-1',
        sourceEventId: 'event-a',
        targetEventId: 'event-b',
        offsetMonths: 3,
      );
      const dep2 = EventDependency(
        id: 'dep-2',
        sourceEventId: 'event-a',
        targetEventId: 'event-b',
        offsetMonths: 3,
      );

      expect(dep1, isNot(equals(dep2)));
    });
  });

  group('DependencyStrength の仕様', () {
    test('hard と soft の2値が存在すること', () {
      expect(DependencyStrength.values.length, 2);
    });

    test('toJson で strength.name が保存されること', () {
      const dep = EventDependency(
        id: 'dep-1',
        sourceEventId: 'a',
        targetEventId: 'b',
        offsetMonths: 0,
        strength: DependencyStrength.hard,
      );

      final json = dep.toJson();

      expect(json['strength'], 'hard');
    });

    test('fromJson で不明な strength 値は soft にフォールバックすること', () {
      final json = {
        'id': 'dep-1',
        'sourceEventId': 'a',
        'targetEventId': 'b',
        'offsetMonths': 0,
        'isAutoGenerated': false,
        'strength': 'unknown-value',
      };

      final dep = EventDependency.fromJson(json);

      expect(dep.strength, DependencyStrength.soft);
    });
  });
}
